# Generated by Django 2.2.1 on 2019-05-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('set_id', models.IntegerField()),
                ('question_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('q_type', models.CharField(choices=[('IMG', 'Image Question'), ('TXT', 'Text Question')], default='TXT', max_length=3)),
                ('question', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('timelimit', models.IntegerField()),
                ('score', models.FloatField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Questionset')),
            ],
        ),
    ]
